version: '3.8'

services:
  # Elasticsearch dedicated server (infra-2)
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - magicain-infra-2

volumes:
  es_data:

networks:
  magicain-infra-2:
    name: magicain-infra-2
    driver: bridge

